//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Num_Invoice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Total_amount { get; set; }
        public string N_Order { get; set; }
    }
}
