//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Num_Invoice { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
